export { default as Avatar } from './Avatar';
export { default as TacerTable } from './TacerTable';
export { default as TacerModal } from './TacerModal';
export { default as TacerSearch } from './TacerSearch';
export { default as TacerForm } from './TacerForm';
export { default as TacerFormModal } from './TacerFormModal';
export { default as OmitText } from './OmitText';
export { default as CopyText } from './CopyText';
export { default as UploadImage } from './UploadImage';
